services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - minio-data:/data

  backend:
    build:
      context: .
      dockerfile: pcd-server/Dockerfile
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BUCKET=pcd
      - MINIO_SECURE=0
      - SQLITE_PATH=/data/pcd.sqlite3
      - PUBLIC_MINIO_URL=http://localhost:9002
    volumes:
      - backend-data:/data
    ports:
      - "8000:8000"
    depends_on:
      - minio

  frontend:
    build:
      context: pcd-viewer
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  minio-data:
  backend-data:


